# Generated by Django 5.2.4 on 2025-07-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='habitcheck',
            name='habit',
        ),
        migrations.RemoveField(
            model_name='habitcheck',
            name='day',
        ),
        migrations.AlterModelOptions(
            name='day',
            options={},
        ),
        migrations.RemoveField(
            model_name='day',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='day',
            name='points',
        ),
        migrations.RemoveField(
            model_name='week',
            name='total_points',
        ),
        migrations.DeleteModel(
            name='GlobalTask',
        ),
        migrations.DeleteModel(
            name='Habit',
        ),
        migrations.DeleteModel(
            name='HabitCheck',
        ),
    ]
