# Generated by Django 6.0.3 on 2026-04-08 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_scheduleitemcompletion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='is_info',
            field=models.BooleanField(default=False, verbose_name='Информационный блок (без чекбокса)'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='journal.scheduletemplate'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Время (опционально)'),
        ),
        migrations.CreateModel(
            name='ScheduleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название секции')),
                ('icon', models.CharField(blank=True, max_length=10, null=True, verbose_name='Иконка (эмодзи)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='journal.scheduletemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='journal.schedulesection'),
        ),
    ]
